source 'https://rubygems.org'

gem 'berkshelf', '~> 3.0.0.beta6'
gem 'chef-sugar'
gem 'chefspec', '~> 3.2.0'
gem 'foodcritic', '~> 3.0.0'
gem 'json', '>= 1.4.4', '<=  1.7.7'
gem 'kitchen-vagrant', '~> 0.14.0'
gem 'rubocop'
gem 'serverspec'
gem 'stove', '~> 2.0.0.beta.2'
gem 'test-kitchen', '~> 1.1.0'
